const DOCUMENT_OWNER_ID_FOREIGN = "document_owner_id_foreign";
const EMPTY_COLLECTION_LENGTH = 0;
const NOT_FOUND_INDEX = -1;

export { DOCUMENT_OWNER_ID_FOREIGN, EMPTY_COLLECTION_LENGTH, NOT_FOUND_INDEX };
