const HOURS = 24;
const MINUTES_IN_HOUR = 60;
const SECONDS_IN_MINUTE = 60;
const MS = 1000;

const TWENTY_FOUR_HOURS_IN_MS =
	HOURS * MINUTES_IN_HOUR * SECONDS_IN_MINUTE * MS;

export { TWENTY_FOUR_HOURS_IN_MS };
