const EMPTY_LENGTH = 0;
const FIRST_INDEX = 0;
const PERCENTAGE_MULTIPLIER = 100;
const MAX_PERCENTAGE = 100;
const INDEX_NOT_FOUND = -1;
const DIVIDER_HALF = 2;
const START_INDEX_FALLBACK = 0;
const ONE_QUANTITY = 1;

export {
	DIVIDER_HALF,
	EMPTY_LENGTH,
	FIRST_INDEX,
	INDEX_NOT_FOUND,
	MAX_PERCENTAGE,
	ONE_QUANTITY,
	PERCENTAGE_MULTIPLIER,
	START_INDEX_FALLBACK,
};
