const PAGE_STEP = 1;
const MIN_NUMBER_OF_PAGES = 1;
const MAX_LOADED_PAGES = 5;
const MIN_SPLIT_POSITION = 25;
const MAX_SPLIT_POSITION = 75;
const INITIAL_SPLIT_POSITION = 50;

export {
	INITIAL_SPLIT_POSITION,
	MAX_LOADED_PAGES,
	MAX_SPLIT_POSITION,
	MIN_NUMBER_OF_PAGES,
	MIN_SPLIT_POSITION,
	PAGE_STEP,
};
