const PAGE_STEP = 1;
const MIN_NUMBER_OF_PAGES = 1;
const MAX_LOADED_PAGES = 5;
const MIN_SPLIT_POSITION = 25;
const MAX_SPLIT_POSITION = 75;
const INITIAL_SPLIT_POSITION = 50;
const INITIAL_ZOOM = 1;
const ZOOM_STEP = 0.1;
const MIN_ZOOM = 1;
const MAX_ZOOM = 3;
const WHEEL_DELTA_THRESHOLD = 0;
const ZOOM_IN_DIRECTION = 1;
const ZOOM_OUT_DIRECTION = -1;

export {
	INITIAL_SPLIT_POSITION,
	INITIAL_ZOOM,
	MAX_LOADED_PAGES,
	MAX_SPLIT_POSITION,
	MAX_ZOOM,
	MIN_NUMBER_OF_PAGES,
	MIN_SPLIT_POSITION,
	MIN_ZOOM,
	PAGE_STEP,
	WHEEL_DELTA_THRESHOLD,
	ZOOM_IN_DIRECTION,
	ZOOM_OUT_DIRECTION,
	ZOOM_STEP,
};
