const PresetValidationRule = {
	DESCRIPTION_MAX_LENGTH: 2000,
	GLOSSARY_ENTRY_MIN_LENGTH: 1,
	ID_MAXIMUM: 2_147_483_647,
	ID_MINIMUM: 1,
	INSTRUCTIONS_MIN_LENGTH: 1,
	MODEL_MIN_LENGTH: 1,
	NAME_MAX_LENGTH: 50,
	NAME_MIN_LENGTH: 1,
} as const;

export { PresetValidationRule };
